export const sections = [
  {
    id: "lean-thinking",
    title: "Lean Thinking",
    subtitle: "Foundational principles from Toyota",
    workbooks: [
      { title: "Toyota Production System", file: "toyota-production-system.pdf" },
      { title: "The Toyota Way", file: "the-toyota-way.pdf" },
    ],
  },
  {
    id: "complexity-thinking",
    title: "Complexity Thinking",
    subtitle: "Understanding uncertainty and complex adaptive systems",
    workbooks: [
      { title: "Complexity Thinking", file: "complexity-thinking.pdf" },
      { title: "Complex Adaptive Systems", file: "complex-adaptive-systems.pdf" },
      { title: "Cynefin Framework", file: "cynefin-framework.pdf" },
      { title: "Sensemaking Systems", file: "sensemaking-systems.pdf" },
      { title: "Weak Signal Detection Part 1", file: "weak-signal-detection-part-1.pdf" },
      { title: "Weak Signal Detection Part 2", file: "weak-signal-detection-part-2.pdf" },
      { title: "Network Analysis", file: "network-analysis.pdf" },
      { title: "Storytelling and Narratives", file: "storytelling-and-narratives.pdf" },
      { title: "Empirical Process Control", file: "empirical-process-control.pdf" },
      { title: "Constraint Management", file: "constraint-management.pdf" },
      { title: "Prototypes", file: "prototypes.pdf" },
      { title: "The OODA Loop", file: "the-ooda-loop.pdf" },
      { title: "Scrum the Toyota Way", file: "scrum-the-toyota-way.pdf" },
    ],
  },
  {
    id: "distributed-leadership",
    title: "Distributed Leadership",
    subtitle: "The behavior patterns of those who lead people and teams",
    workbooks: [
      { title: "Psychological Safety", file: "psychological-safety.pdf" },
      { title: "Active Listening", file: "active-listening.pdf" },
      { title: "Leader's Intent", file: "leaders-intent.pdf" },
      { title: "Shared Mental Models", file: "shared-mental-models.pdf" },
      { title: "Wardley Maps", file: "wardley-maps.pdf" },
      { title: "Decision-Making", file: "decision-making.pdf" },
      { title: "Bias Towards Action", file: "bias-towards-action.pdf" },
      { title: "Collaboration", file: "collaboration.pdf" },
      { title: "Coaching and Mentoring", file: "coaching-and-mentoring.pdf" },
      { title: "Complex Facilitation Part 1", file: "complex-facilitation-part-1.pdf" },
      { title: "Complex Facilitation Part 2", file: "complex-facilitation-part-2.pdf" },
      { title: "Organizational Design Part 1", file: "organizational-design-part-1.pdf" },
      { title: "Organizational Design Part 2", file: "organizational-design-part-2.pdf" },
    ],
  },
  {
    id: "team-science",
    title: "Team Science",
    subtitle: "The science of teams, their interdependencies and interactions",
    workbooks: [
      { title: "Teamwork Training", file: "teamwork-training.pdf" },
      { title: "Human-Centered Design", file: "human-centered-design.pdf" },
      { title: "Team Design", file: "team-design.pdf" },
      { title: "Goal Identification", file: "goal-identification.pdf" },
      { title: "Situational Awareness", file: "situational-awareness.pdf" },
      { title: "Developing Cognitions", file: "developing-cognitions.pdf" },
      { title: "Influencing Conditions", file: "influencing-conditions.pdf" },
      { title: "Team Learning", file: "team-learning.pdf" },
      { title: "Team Effectiveness", file: "team-effectiveness.pdf" },
      { title: "Red Teaming", file: "red-teaming.pdf" },
      { title: "Multiteam Systems", file: "multiteam-systems.pdf" },
    ],
  },
];
