export const sections = [
  {
    id: "lean-thinking",
    title: "Lean Thinking",
    subtitle: "Foundational principles from Toyota",
    workbooks: [
      { title: "Toyota Production System", file: "Workbook - Toyota Production System.pdf" },
      { title: "The Toyota Way", file: "Workbook - The Toyota Way.pdf" },
    ],
  },
  {
    id: "complexity-thinking",
    title: "Complexity Thinking",
    subtitle: "Understanding uncertainty and complex adaptive systems",
    workbooks: [
      { title: "Complexity Thinking", file: "Workbook - Complexity Thinking.pdf" },
      { title: "Complex Adaptive Systems", file: "Workbook - Complex Adaptive Systems.pdf" },
      { title: "Cynefin Framework", file: "Workbook - Cynefin Framework.pdf" },
      { title: "Sensemaking Systems", file: "Workbook - Sensemaking Systems.pdf" },
      { title: "Weak Signal Detection Part 1", file: "Workbook 1 - Weak Signal Detection.pdf" },
      { title: "Weak Signal Detection Part 2", file: "Workbook 2 - Weak Signal Detection.pdf" },
      { title: "Network Analysis", file: "Workbook - Network Analysis.pdf" },
      { title: "Storytelling and Narratives", file: "Workbook - Storytelling and Narratives.pdf" },
      { title: "Empirical Process Control", file: "Workbook - Empirical Process Control.pdf" },
      { title: "Constraint Management", file: "Workbook - Constraint Management.pdf" },
      { title: "Prototypes", file: "Workbook - Prototypes.pdf" },
      { title: "The OODA Loop", file: "Workbook - The OODP Loop.pdf" },
      { title: "Scrum the Toyota Way", file: "Workbook - Scrum the Toyota Way.pdf" },
    ],
  },
  {
    id: "distributed-leadership",
    title: "Distributed Leadership",
    subtitle: "The behaviour patterns of those who lead people and teams",
    workbooks: [
      { title: "Psychological Safety", file: "Workbook - Psychological Safety.pdf" },
      { title: "Active Listening", file: "Workbook - Active Listening.pdf" },
      { title: "Leaders Intent", file: "Workbook - Leader's Intent.pdf" },
      { title: "Shared Mental Models", file: "Workbook - Shared Mental Models.pdf" },
      { title: "Wardley Maps", file: "Workbook - Wardley Maps.pdf" },
      { title: "Decision-Making", file: "Workbook - Decision-Making.pdf" },
      { title: "Bias Towards Action", file: "Workbook - Bias Towards Action.pdf" },
      { title: "Collaboration", file: "Workbook - Collaboration.pdf" },
      { title: "Coaching and Mentoring", file: "Workbook - Coaching and Mentoring.pdf" },
      { title: "Complex Facilitation Part 1", file: "Workbook 1 - Complex Facilitation.pdf" },
      { title: "Complex Facilitation Part 2", file: "Workbook 2 - Complex Facilitation.pdf" },
      { title: "Organisational Design Part 1", file: "Workbook 1 - Organizational Design.pdf" },
      { title: "Organisational Design Part 2", file: "Workbook 2 - Organizational Design.pdf" },
    ],
  },
  {
    id: "team-science",
    title: "Team Science",
    subtitle: "The science of teams, their interdependencies and interactions",
    workbooks: [
      { title: "Teamwork Training", file: "Workbook - Teamwork Training.pdf" },
      { title: "Human-Centred Design", file: "Workbook - Human-Centred Design.pdf" },
      { title: "Team Design", file: "Workbook - Team Design.pdf" },
      { title: "Goal Identification", file: "Workbook - Goal Identification.pdf" },
      { title: "Situational Awareness", file: "Workbook - Situational Awareness.pdf" },
      { title: "Developing Cognitions", file: "Workbook - Developing Cognitions.pdf" },
      { title: "Influencing Conditions", file: "Workbook - Influencing Conditions.pdf" },
      { title: "Team Learning", file: "Workbook - Team Learning.pdf" },
      { title: "Team Effectiveness", file: "Workbook - Team Effectiveness.pdf" },
      { title: "Red Teaming", file: "Workbook - Red Teaming.pdf" },
      { title: "Multiteam Systems", file: "Workbook - Multiteam Systems.pdf" },
    ],
  },
];
